### ISSUE TITLE
Six stopped going to normal mode on opening files 100 % of the times

### ISSUE THREAD

**Issue by nikitavoloboev** [guillermooo/Six#205] opened 2018-06-16 13:14 UTC
It happens sometimes that I open a file and I am not in normal mode:

![2018-06-16 at 15 13](https://user-images.githubusercontent.com/6391776/41498860-d72225d6-7177-11e8-9162-2d0250811964.png)

This started happening with some recent updates as before I never had that problem. I am using latest version of Six (`v0.8.91`) and Sublime Text editor.

**Comment by guillermooo** [comment] 2018-06-16 15:35
@nikitavoloboev Most files open in normal mode for me. There is a case where they don't: when I use `subl` as my `$EDITOR` and git opens the file. In that case, the _second_ file that git opens (for example, while `rebase`ing) starts in insert mode.

Do you have any specific repro steps?

I will give this a try on macOS, but on Windows it doesn't seem to happen 100% of the time.

**Comment by nikitavoloboev** [comment] 2018-06-16 16:01
> Do you have any specific repro steps?

I can reproduce it 100 % of the times. I open a file, and go to Insert mode. Then close the tab with cmd + w and try open any other file from Finder for example. The file will be opened with Insert mode, not Normal.

Before it always went to Normal mode as is intentional. After some update this broke it seems.

**Comment by guillermooo** [comment] 2018-06-16 16:10
OK. I can confirm the issue on macOS when:

1. User goes to insert mode
2. User closes last view with _native_ ST key binding
3. The next time ST starts, it istarts in insert mode (no status bar mode hint)

@nikitavoloboev Could you please run this in the ST console and tell me what you see when this happens?

```python
from Six._init_ import editor
editor.active_mode.name
```

**Comment by guillermooo** [comment] 2018-06-16 16:12
The same repro steps do **not** work on Windows.

**Comment by nikitavoloboev** [comment] 2018-06-16 16:16
> Could you please run this in the ST console and tell me what you see when this happens?

I get:

`'normal'`

**Comment by nikitavoloboev** [comment] 2018-06-16 16:28
I am certain this worked on macOS as intended quite a few releases back. I have been using Six for over a year now.

**Comment by guillermooo** [comment] 2018-06-16 16:30
I'll check past versions in macOS and see if I can find the issue.

**Comment by nikitavoloboev** [comment] 2018-06-16 16:31
I am using 10.11.6 currently. But plan to upgrade to 10.14 soon.

**Comment by guillermooo** [comment] 2018-06-16 16:43
As far as I can tell, this bug has been there since the very first version of Six.

More details:

I can't repro the bug if I exit the application (one transient view, insert mode) by pressing `cmd+q`. In that case, Six starts in normal mode the next time (running `subl` from the command line, no file path given or Finder).


So, so far, it seems this only happens if you enter insert mode in the last open file and close it by pressing `cmd+w`.

**Comment by nikitavoloboev** [comment] 2018-06-16 16:47
Or cmd + shift + w. Which effectively closes the window and all the tabs in the current window.

**Comment by guillermooo** [comment] 2018-06-16 19:51
Maybe related: https://developer.apple.com/design/human-interface-guidelines/macos/app-architecture/restoring-state/

**Comment by guillermooo** [comment] 2018-06-16 20:33
For reference:

* https://support.apple.com/kb/ph25174?locale=en_US
*https://support.apple.com/kb/PH25079?locale=en_US&viewlocale=en_US

**Comment by guillermooo** [comment] 2018-06-16 20:35
In sum, it looks like macOS keeps apps open after the user closes them (!?) in certain ways, so naturally the init process does not happen again when the user restores the app.

The only true way of exiting a macOS app is "quitting" the app.

Any other way of closing windows does not quit the app; the app stays around in a windowless state.

**Comment by guillermooo** [comment] 2018-06-17 17:05
@nikitavoloboev The bug should be partially fixed in 0.8.92-dev.00.3.

To obtain this version, you need to add the following to your Package Control config file:

```json
"install_prereleases": ["Six"]
```

**Comment by nikitavoloboev** [comment] 2018-06-20 21:57
Hi @guillermooo. This update actually introduced a really bad change. Now if I am in insert mode editing some text. Then I switch to my browser with cmd + tab and go back. The mode will always be Normal. I want it to remember the mode I left the tab in.

**Comment by guillermooo** [comment] 2018-06-21 04:35
Correction: not only insert mode should be preserved in the first case mentioned aboe, but any active mode at that time.

**Comment by guillermooo** [comment] 2018-06-21 04:44
@nikitavoloboev Confirmed working as expected on macOS. The active mode is preserved when switching to an external app and back.

If you switch back extremely fast, the mode will be reset, though. This is because Six uses a timer to detect this case. But if you do that, switching to an external app is pointless because you can't see what's in it. Could it be that you are switching bak to Six very quickly? I can decrease the timeout period, but it will probably cause Six to get confused about when it is switching back from an external app vs between Sublime Text tabs.

**Comment by guillermooo** [comment] 2018-06-21 05:18
@nikitavoloboev 

Insert mode is always sticky for me. No matter whether I switch to an external app and back or between ST tabs. Implementation-wise, insert mode is unaffected by the timer. Could you please confirm that insert mode is always sticky for you too?

Visual mode, however, gets reset to normal mode based on the timer. The current timeout is set to 300ms. If've now dialled it down to 85ms because if I try really hard, I am faster than the timeout up to 90ms. But this could cause inconsistencies when switching between tabs. We'll see how the new value works.

**Comment by guillermooo** [comment] 2018-06-21 07:20
I've found the issue. The reported problem should only happen when there's a single view open. The bug was introduced with the fix for macOS not switching to normal mode when ST comes back from the macOS app suspended state.

**Comment by nikitavoloboev** [comment] 2018-06-21 13:13
Also @guillermooo, is it possible to please speed up how fast Six enters into normal mode on opening files. Ideally I want it to be instant (same as Vim). Right now, I open a new file in Sublime and I have to wait ~ 4 seconds for it to go into normal mode. I think before it was much faster.

**Comment by guillermooo** [comment] 2018-06-21 16:13
The activation issue should be solved in the latest dev build.

About slow start, my experience is quite the opposite---start time has been reduced lately. I'll profile and see what can be done. Sublime Text loads packages in alphabetical order, so Six gets a rather low precedence. I'm not sure that can be changed, but I'll take a look. In fact, Six should load first, as it takes over user keyboard input and has no dependencies.

**Comment by nikitavoloboev** [comment] 2018-06-21 20:45
I can confirm that new update now correctly saves the state of the mode so switching to a window will not always reset to normal mode.

The slowing down of how long it takes to go to normal mode in opening files is still a huge issue for me though. It literally takes ~ 4/5 seconds to go to normal mode. 😞

**Comment by guillermooo** [comment] 2018-06-21 21:07
I see start-up times of about 2.5s. It isn't great, but bearable. 4/5s sounds like too long. Have you got any other packages installed? Are you doing a cold start every time? (Full loading of packages.) Do you open files from the command line, Finder...? Are you using a project or opening files here and there?

**Comment by nikitavoloboev** [comment] 2018-06-21 21:33
[Here](https://github.com/nikitavoloboev/dotfiles/blob/master/sublime/Package%20Control.sublime-settings) are all the packages I have installed.

I am not doing a cold restart every time. I have Sublime Text always opened but usually with no active window. I then open the file I need with [Alfred](https://www.alfredapp.com) which is essentially like opening a file from Finder in Sublime Text.

It's strange though. Sometimes it is instant in being in normal mode (less than 1 second). And other times it really does take ~ 3/4 seconds to go to normal mode. I do know that I did not have this issue before though and it turned to normal mode fast and I think all the time.

I am not using any projects, I just open files here and there.

**Comment by nikitavoloboev** [comment] 2018-06-21 21:51
I also want to note that sometimes Six breaks for me fully and will never go into normal mode. I am forced to quit and start Sublime Text to get it working.

I am happy to send any logs I can to help solve this issue.

**Comment by guillermooo** [comment] 2018-06-21 22:45
Thank you for the additional info.

>I also want to note that sometimes Six breaks for me fully and will never go into normal mode. I am forced to quit and start Sublime Text to get it working.

Is this also a recent issue or something you've experienced now and then all along?

(I am going to try and fix a pending issue with repeating after a macro and then I'll start using macOS for a while to see if I can repro your issues.)

**Comment by nikitavoloboev** [comment] 2018-06-21 22:49
> Is this also a recent issue or something you've experienced now and then all along?

It started happening very often now, I don't think this happened before to me and I use Sublime Text a lot.

Also besides the normal mode issue where it takes ~ 4 to go into it. I started getting weird delays in rendering a file sometimes where it takes a bit to render a file where as before I didn't have this issue. I haven't downloaded any plugins for quite some time now and it all started happening after some update to Six (not sure which).

Hopefully you can reproduce these issues on mac as you use it and it can be fixed. Thank you.

**Comment by guillermooo** [comment] 2018-06-22 07:57
Closing in favor of #208 for clarity.

**Closed** 2018-06-22 07:58 UTC
Labels: area:mode, area:ui, bug
