### ISSUE TITLE
Doesn't seem to work after installing

### ISSUE THREAD

**Issue by Asuza** [guillermooo/Six#200] opened 2018-04-18 19:57 UTC
I'm not really sure if I need to activate the plugin, but there are a lot of errors going on and no vim-like commands seem to be doing anything.

Here's some output:
```
2018-04-18 14:51:40,734 - CRITICAL - Six.lib.editor_internal - Unexpected error.
2018-04-18 14:51:40,734 - ERROR - Six.lib.editor_internal - list index out of range
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\lib\editor_internal.py", line 38, in handle
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\lib\editor_internal.py", line 92, in _handle_ui
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\lib\command_state.py", line 724, in active_mode
2018-04-18 14:51:40,735 - INFO - Six.lib.editor_internal - Trying to reenter Normal mode...
2018-04-18 14:51:40,735 - CRITICAL - Six.lib.command_state - cannot enter unavailable mode: normal (<Esc>)
2018-04-18 14:51:40,735 - CRITICAL - Six.lib.editor_internal - Could not reenter Normal mode. Please restart Sublime Text.
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\lib\editor_internal.py", line 144, in _handle_exception
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\lib\command_state.py", line 874, in enter_mode
```

**Comment by guillermooo** [comment] 2018-04-24 07:15
Have you disabled Vintage/Vintageous? Those plugin will interfere with Six.

**Comment by Asuza** [comment] 2018-05-17 03:08
Sorry, I must have forgotten to respond. No plugins were enabled that would interfere with Six. I should have made it clear that my name is not _guillermo_, which the plugin is referencing, and I'm using Linux, while it's trying to access a Windows file path. This is definitely not a configuration issue.

**Comment by Asuza** [comment] 2018-05-17 03:08
@guillermooo, I don't see an option to re-open this issue, so I'm mentioning you here.

**Comment by guillermooo** [comment] 2018-05-17 05:33
I will try to take a look on Linux.

**Comment by guillermooo** [comment] 2018-05-17 05:43
@Asuza I've just done a fresh install of Six via Package Control on a Xubuntu VM and it works fine for me the first time.

The wrong name in paths should not be an issue.


My user's `.sublime-settings` file only contains the following:

```
{
    {
        "ignored_packages": ["Vintage"]
    }
}
```

**Comment by eproxus** [comment] 2018-05-25 11:38
Can reproduce. Fresh install of build 3176, installed Sublime Six but nothing happens. Vintage is in the ignored list by default in Sublime Text.

**Comment by guillermooo** [comment] 2018-06-07 04:10
@Asuza I routinely test Six on all three OSes and I can't reproduce anything like this error. Also, I haven't received similar reports from other users. I will close this now, but feel free to reply and mention me if you are still experiencing the issue.

**Closed by guillermooo** 2018-06-07 04:10 UTC
