### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rhelsing** [guillermooo/Six#154] opened 2017-07-21 19:22 UTC
Not sure whats happening but when I close sublime on Mac (only closing all windows, not terminating process) and reopen, I get this error when I open a file. If I completely close sublime and reopen, six seems to start properly.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 664, in on_post_text_command
    callback.on_post_text_command(v, name, args)
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\commands\event_mouse.py", line 39, in on_post_text_command
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\lib\command_state.py", line 986, in active_mode
IndexError: list index out of range
```

**Comment by rhelsing** [comment] 2017-07-21 19:23
@guillermooo looks like it's trying to load a file from your machine maybe?

**Comment by guillermooo** [comment] 2017-07-21 19:24
Most probably an issue with view activation. It looks like there is no selection available.

(I'm surprised to see my local path there. I guess compiling to .pyc does that.)

**Comment by guillermooo** [comment] 2017-07-21 19:26
So does this happen when you close all views in the app and you are left with an empty window?

**Comment by rhelsing** [comment] 2017-07-21 19:29
If you don't see an obvious fix, I will try to figure out how to consistently recreate the issue for now..

**Comment by guillermooo** [comment] 2017-07-21 19:38
I think there's a bit of custom logic for Mac because Six wouldn't catch the on_activated view event otherwise. It might be related to that. I'll try to use my Mac for a few days.

**Comment by guillermooo** [comment] 2017-07-22 16:06
FWIW, I'm getting this on Windows when running the test suite. Not sure if it's related. Also, I improved logging recently, so this is why these errors are being logged now. They may have been lurking there for a while.

**Comment by guillermooo** [comment] 2017-07-22 16:06
Well, for me at least, they are logged. @rhelsing Do you get log entries for ERROR or CRITICAL too?

**Comment by rhelsing** [comment] 2017-07-22 16:11
Just opened to check and the issue was happening.. opened a file, didn't see anything in the console, as soon as I pressed esc, i, esc I got this:

```
2017-07-22 11:10:41,476 - Six.lib.command_state - CRITICAL - Unexpected error.
2017-07-22 11:10:41,476 - Six.lib.command_state - ERROR - 'NoneType' object has no attribute 'get'
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\lib\command_state.py", line 1046, in handle
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\lib\command_state.py", line 1107, in _handle
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\lib\command_state.py", line 373, in enter
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\lib\command_state.py", line 1326, in store_command_for_repeating
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\plugin\window_settings.py", line 19, in __getitem__
2017-07-22 11:10:41,477 - Six.lib.command_state - INFO - Trying to reenter Normal mode...
2017-07-22 11:10:41,477 - Six.lib.command_state - CRITICAL - cannot enter unavailable mode: normal (<Esc>)
2017-07-22 11:10:41,477 - Six.lib.command_state - CRITICAL - Could not reenter Normal mode. Please restart Sublime Text.
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\lib\command_state.py", line 1091, in handle
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\lib\command_state.py", line 1227, in enter_mode
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 664, in on_post_text_command
    callback.on_post_text_command(v, name, args)
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\commands\event_mouse.py", line 39, in on_post_text_command
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\lib\command_state.py", line 986, in active_mode
IndexError: list index out of range
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 664, in on_post_text_command
    callback.on_post_text_command(v, name, args)
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\commands\event_mouse.py", line 39, in on_post_text_command
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\lib\command_state.py", line 986, in active_mode
IndexError: list index out of range
```

**Comment by guillermooo** [comment] 2017-07-22 16:15
Thanks for that. It does look like Six isn't properly initialized for some reason. Ugh.

**Comment by guillermooo** [comment] 2017-07-23 09:53
On Ubuntu, I get NoneType has not get... error after closing the last view in the app (ST remains open and instantly creates a new view).

**Comment by guillermooo** [comment] 2017-07-24 08:35
The error mentioned in my previous post has been solved. Six now ensures to always create a new view when none is available, as transient views seem to behave differently with regards to events compared to regular views.

Still investigating the Mac issue.

**Comment by guillermooo** [comment] 2017-07-25 05:43
@rhelsing Managed to repro following these steps:

```
Open ST with just one empty view
Cmd+,
:q
```

**Comment by guillermooo** [comment] 2017-07-25 06:11
It seems Six correctly initializes when no open view is available (only a transient view), but fails to go from 1 regular view to 0 regular views after closing the last regular view when the app is already running.

**Comment by guillermooo** [comment] 2017-07-25 06:19
So it seems you can have an app active with no available windows in MacOS. I'm getting sporadic init errors depending on whether ST was active+no window before or no active+no window.

If I close all views via `:q` in a running instance of ST, I end up in the active+no windows state.

By active I mean the app is visible via `Cmd+Tab`, I wish I new MacOS terminology better.

**Comment by guillermooo** [comment] 2017-07-25 06:44
The test suite also fails if started from a new, single, transient view, but it completes successfully if started from a regular, unsaved, single view.

I need to try this on Windows and Linux too.

**Comment by guillermooo** [comment] 2017-07-25 17:55
Apparently this bug was affecting all three platforms.

I could reproduce it by opening the Preferences window and returning to the previous window (closing Preferences), by closing all open views via `:q`, `Ctrl+W` in insert mode or by clicking on the close button.

I've made a fix that at least should avoid the problem, but further fine tuning will be necessary.

**Comment by guillermooo** [comment] 2017-07-25 18:29
@rhelsing I've pushed a new build. Let me know if it fixes this issue for you.

**Closed** 2017-07-28 18:15 UTC
