### ISSUE TITLE
Issue with files wrongly being marked as changed

### ISSUE THREAD

**Issue by n00ge** [guillermooo/Six#110] opened 2017-05-15 21:34 UTC
Hey Guillermo, great work on Sublime Six. 

Question for you. I have been seeing an issue with it since installation (been using it since you pushed the message to old vintageous users) where the file is wrongly marked as changed. It occurs when I save a file. I believe it's related to the user preference `"trim_trailing_white_space_on_save": true` being enabled. If I am in insert mode, save the file when on a line that had indentation without trailing code, and immediately switch to a new tab after a second or two it then shows the pencil icon in the tab I just saved as if there were a new change. 

Let me know if there is anything I can do to help troubleshoot.

**Comment by rhelsing** [comment] 2017-05-15 21:44
I believe I have this issue too and what I was referring to earlier. I also have this setting enabled.

**Comment by guillermooo** [comment] 2017-05-16 19:19
Hey @n00ge, hope all's going well!

I think Vintageous used to have this issue too. I think Six needs to `unmark_groups_for_glueing` if no edits were made in insert mode.

@rhelsing I probably misunderstood your error report; sorry about that! At least now I know what the issue is.

**Comment by guillermooo** [comment] 2017-06-17 07:01
Repro steps:

1. Enter insert mode.
2. On a non-empty line, add trailing ws.
3. Save via Ctrl+Save in insert mode
4. trim_trailing_white_space kicks in
5. File is now saved
6. Exit insert mode

The dirty indicator is shown in the tab.

**Comment by guillermooo** [comment] 2017-06-17 07:32
This is a summary of my findings so far:

The issue arises when the user saves in insert mode and, as a result of that operation, `trim_trailing_white_space` is triggered.

After the above steps, when exiting insert mode, Six executes `mark_undo_groups_for_gluing` as usual. At this point, `view.is_dirty()` returns `False`.  Sublime Text reports the same `view.change_count()` before and after this command; therefore, the `view.is_dirty()` method should return `False` before and after. However, this is not the case and, in this particular case, `view.is_dirty()`, for some reason, will always return `True` after the command.

Note that this does not seem to happen when the user exits insert mode after having appended non-white-space text only.

@nooge The user should not be able to save in insert mode to begin with, but given that they can (either by using Ctrl+Save or via menus or commands), my suggestion is to make Six save the file again if it can detect the inconsistency.

**Comment by guillermooo** [comment] 2017-06-20 05:31
The solution seems to be to call `unmark_undo_groups_for_gluing` in an `on_post_save` event hander.

**Comment by guillermooo** [comment] 2017-06-21 05:40
0.1.55

**Comment by guillermooo** [comment] 2017-06-21 05:41
I think this is solved now. Closing.

**Closed by guillermooo** 2017-06-21 05:40 UTC

**Comment by n00ge** [comment] 2017-06-21 21:11
Looks good. Thanks!
